executable              = run_data.sh
arguments               = $(dir)
Initialdir              = /afs/cern.ch/user/y/yuekai/EFT-ttbar/QCD_ES/2015/condor_out_data/$(dir)
						
output                  = run.out
error                   = run.err
log                     = run.log
						
RequestMemory           = 2000
ShouldTransferFiles     = NO
+JobFlavour             = "nextweek"
x509userproxy           = $ENV(HOME)/temp/x509up
Queue dir from ./condor_list_data.txt
