executable              = run_MC.sh
arguments               = $(dir)
Initialdir              = /afs/cern.ch/user/y/yuekai/ttbar/select/2017/condor_out_MC/$(dir)
						
output                  = run.out
error                   = run.err
log                     = run.log
						
RequestMemory           = 2000
ShouldTransferFiles     = NO
+JobFlavour             = "testmatch"
x509userproxy           = $ENV(HOME)/temp/x509up
Queue dir from ./condor_list_MC.txt
