executable              = run_sys.sh
arguments               = $(dir)
Initialdir              = /afs/cern.ch/user/y/yuekai/ttbar/condor/select/2018/condor_out_mtop/$(dir)
						
output                  = run.out
error                   = run.err
log                     = run.log
						
RequestMemory           = 2000
ShouldTransferFiles     = NO
+JobFlavour             = "testmatch"
x509userproxy           = $ENV(HOME)/temp/x509up
Queue dir from ./condor_list_mtop.txt
